<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('khairat_kematian_funds', function (Blueprint $table) {
            $table->id('fund_id'); // Primary key: fund_id
            $table->string('No_Ahli'); // Foreign key referencing No_Ahli from users
            $table->string('bill_code')->unique(); // Store the Bill Code generated by ToyyibPay
            $table->decimal('Payment_amount', 8, 2); // Payment amount with 2 decimal places
            $table->string('payment_status'); // Payment status (e.g., 'success', 'failed')
            $table->timestamp('payment_date'); // Payment date
            $table->string('Payment_For'); // Description of payment (e.g., 'Khairat Kematian')

            // Foreign key constraint referencing the No_Ahli from users
            $table->foreign('No_Ahli')
                ->references('No_Ahli') // references the No_Ahli field in users table
                ->on('users') // from the users table
                ->onDelete('cascade'); // Optionally delete related records when user is deleted

            $table->timestamps(); // Adds created_at and updated_at automatically
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('khairat_kematian_funds');
    }
};
